# Generated by Django 5.0.3 on 2025-04-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, default='qKO6oQFCTWMVYYI1XDntjse1qSjiCvNEuoIiMqQGtBHq2pNymIv8ReE0NreecpHFcONrDt1K', max_length=108, null=True, verbose_name='Active Code'),
        ),
    ]
