# Generated by Django 5.0.3 on 2025-04-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, default='7IMsVvzrGcpaENVvRrmYz56GkWy5TIol1co3KaVMYXex2W8VnE83b8UyEQDubDAwWyJyDYLJ', max_length=108, null=True, verbose_name='Active Code'),
        ),
    ]
