# Generated by Django 5.0.3 on 2025-04-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, default='HoAfqqZA2Uu0o8o3FkSSwO7QWuQd5FJQasHllvpB29p0u48WjoCqXuel3l69qdh85hd7Qn7u', max_length=108, null=True, verbose_name='Active Code'),
        ),
    ]
