# Generated by Django 5.0.3 on 2024-09-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_setting', models.BooleanField(blank=True, default=False, verbose_name='main setting')),
                ('site_name', models.CharField(max_length=72, verbose_name='site name')),
                ('site_name_fa', models.CharField(max_length=72, null=True, verbose_name='site name')),
                ('site_name_en', models.CharField(max_length=72, null=True, verbose_name='site name')),
                ('site_url', models.CharField(max_length=72, verbose_name='site domain')),
                ('site_logo', models.ImageField(blank=True, upload_to='images/site_module/', verbose_name='site logo')),
                ('site_icon', models.ImageField(blank=True, null=True, upload_to='images/site_module/', verbose_name='site icon')),
                ('slide_show_number', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=2, verbose_name='main slide show number')),
                ('address', models.TextField(blank=True, max_length=72, null=True, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=72, null=True, verbose_name='phone number')),
                ('email', models.CharField(blank=True, max_length=72, null=True, verbose_name='email')),
                ('copy_right', models.TextField(verbose_name='copyright')),
                ('copy_right_fa', models.TextField(null=True, verbose_name='copyright')),
                ('copy_right_en', models.TextField(null=True, verbose_name='copyright')),
                ('services', models.TextField(null=True, verbose_name='services')),
                ('services_fa', models.TextField(null=True, verbose_name='services')),
                ('services_en', models.TextField(null=True, verbose_name='services')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='about us')),
                ('about_us_fa', models.TextField(blank=True, null=True, verbose_name='about us')),
                ('about_us_en', models.TextField(blank=True, null=True, verbose_name='about us')),
                ('preload_icon', models.ImageField(blank=True, db_index=True, null=True, upload_to='images/site_module/', verbose_name='preload icon')),
                ('home_img', models.ImageField(blank=True, null=True, upload_to='images/site_module/', verbose_name='home image')),
                ('user_img', models.ImageField(null=True, upload_to='images/site_module/', verbose_name='default user profile')),
                ('account_img', models.FileField(blank=True, null=True, upload_to='images/site_module/', verbose_name='account page image')),
                ('contact_img', models.FileField(blank=True, null=True, upload_to='images/site_module/', verbose_name='contact us page image')),
                ('social_1_icon', models.ImageField(blank=True, null=True, upload_to='images/site_module/', verbose_name='social media icon')),
                ('social_1', models.CharField(blank=True, max_length=144, null=True, verbose_name='social media above link')),
                ('social_2_icon', models.ImageField(blank=True, null=True, upload_to='images/site_module/', verbose_name='social media icon')),
                ('social_2', models.CharField(blank=True, max_length=144, null=True, verbose_name='social media above link')),
                ('social_3_icon', models.ImageField(blank=True, null=True, upload_to='images/site_module/', verbose_name='social media icon')),
                ('social_3', models.CharField(blank=True, max_length=144, null=True, verbose_name='social media above link')),
                ('social_4_icon', models.ImageField(blank=True, null=True, upload_to='images/site_module/', verbose_name='social media icon')),
                ('social_4', models.CharField(blank=True, max_length=144, null=True, verbose_name='social media above link')),
            ],
            options={
                'verbose_name': 'site setting',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='MainSlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='if you choose all products not matter', max_length=128)),
                ('all', models.BooleanField(default=False, verbose_name='choose all products')),
                ('order_by', models.CharField(choices=[('releaseDate', 'releaseDate'), ('-releaseDate', '-releaseDate'), ('addDate', 'addDate'), ('-addDate', '-addDate'), ('price', 'price'), ('-price', '-price'), ('discount', 'discount'), ('-discount', '-discount'), ('title', 'title'), ('-title', '-title')], default='releaseDate', max_length=256, verbose_name='order by')),
                ('choice_field', models.CharField(blank=True, choices=[('product_list', 'لیست محصولات'), ('product_detail', 'جزِییات محصولات'), ('about_us', 'درباره ما')], default='', max_length=256, null=True, verbose_name='choose class')),
                ('show_list', models.ManyToManyField(blank=True, related_name='show_list', to='products.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'main slide show',
                'verbose_name_plural': 'main slide show',
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=32, verbose_name='title')),
                ('title_fa', models.CharField(default=None, max_length=32, null=True, verbose_name='title')),
                ('title_en', models.CharField(default=None, max_length=32, null=True, verbose_name='title')),
                ('order_by', models.CharField(choices=[('releaseDate', 'releaseDate'), ('-releaseDate', '-releaseDate'), ('addDate', 'addDate'), ('-addDate', '-addDate'), ('price', 'price'), ('-price', '-price'), ('discount', 'discount'), ('-discount', '-discount'), ('title', 'title'), ('-title', '-title'), ('most-visit', 'most-visit'), ('most-bought', 'most-bought')], default='releaseDate', max_length=256, verbose_name='order by')),
                ('show_order', models.IntegerField(default=1, verbose_name='show order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='deleted')),
                ('note', models.CharField(default='if you choose parent category, category not matter', max_length=128)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.productcategory', verbose_name='category')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='products.parentcategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'slide show',
                'verbose_name_plural': 'slide shows',
            },
        ),
    ]
