# Generated by Django 5.0.3 on 2024-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('email', models.EmailField(max_length=300, verbose_name='email')),
                ('subject', models.CharField(max_length=300, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='send date')),
                ('response', models.TextField(blank=True, null=True, verbose_name='answer')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='read by admin')),
            ],
            options={
                'verbose_name': 'contact us list',
                'verbose_name_plural': 'contact us list',
            },
        ),
    ]
