"""
Django settings for django5_gamestore project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4+&$062z0ak*vw*8706*e*4!y76dbra5y+*4gis%0_)uo^$0^2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []
# DEBUG = False
# ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # needed for sessions default expire date(2 weeks)
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 'django.forms'
    # internal apps:
    'account',
    'contact',
    'home',
    'products',
    'site_module',
    'polls',
    'user_panel',
    'cart',
    'admin_panel',
    # external apps:
    'django_render_partial',  # need install package : pip install django-render-partial
    # should go after your apps : delete unused data (images)
    'django_cleanup.apps.CleanupConfig',
    'sorl.thumbnail',  # change image size
    'jalali_date',
    'widget_tweaks',
    'rosetta',
    'modeltranslation',
    'captcha',
    'django_recaptcha',
    # DRF
    'rest_framework',
    # jwt
    'rest_framework_simplejwt',
    "corsheaders",
    'drf_spectacular',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # needed for sessions
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # new place is important
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django5_gamestore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django5_gamestore.wsgi.application'

AUTH_USER_MODEL = 'account.User'  # add custom auth
LOGIN_URL = 'sign_in_page'  # instead of login

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 'ENGINE': 'django.db.backends.mysql',
        'NAME': BASE_DIR / 'db.sqlite3',
        # USER, PASSWORD
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# multi language
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGES = [
    ('fa', 'فارسی'), # Persian
    ('en', 'English')
]

ROSETTA_LANGUAGES = [
    ('fa_IR', 'فارسی'),  # name created in locate folder
    ('en_US', 'English')
]

LOCALE_PATHS = [
    BASE_DIR / 'locale'
]

LANGUAGE_CODE = 'en-us'  # change admin panel language
# LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, "uploads")
MEDIA_URL = '/medias/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),  # needed to search main file(not apps)
    BASE_DIR / "static"
)
STATIC_ROOT = BASE_DIR / 'static_cdn'
# session part
# SESSION_COOKIE_AGE = 10  # base on second (expire date)
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Todo: remove email and password
# set Email :
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'GameStorePersia@gmail.com' # Your email
EMAIL_HOST_PASSWORD = 'igdvffwibhiqxjuo' # Your App Password
EMAIL_PORT = 587

# set payment getaway
# SANDBOX MODE
MERCHANT = "3344b9a6-****-****-****-4c157dc7329c"
SANDBOX = True

# jalali date
# default settings (optional)
JALALI_DATE_DEFAULTS = {
    'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            # loading datepicker
            'admin/js/django_jalali.min.js',
            # OR
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/calendar.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js',
            # 'admin/js/main.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}

# reCaptcha Google
RECAPTCHA_PUBLIC_KEY = ''
RECAPTCHA_PRIVATE_KEY = ''
RECAPTCHA_DOMAIN = 'www.reza-taheri.ir'

# captcha (Current)
CAPTCHA_FONT_SIZE = 50
CAPTCHA_IMAGE_SIZE = (160, 60)
CAPTCHA_2X_IMAGE = False
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge' characters
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge' # numbers
# CAPTCHA_FOREGROUND_COLOR = '#ffffff'
# CAPTCHA_BACKGROUND_COLOR = '#2a2b33'

# Rest Framework
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {  # globals
    # Swagger (DRF_SPECTACULAR)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Game Store API',
    'DESCRIPTION': 'API of reza-taheri.ir',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
    # list of authentication/permission classes for spectacular's views.
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'],
    # None will default to DRF's AUTHENTICATION_CLASSES
    'SERVE_AUTHENTICATION': ['rest_framework.authentication.BasicAuthentication'],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=3),
}
