# Generated by Django 5.0.3 on 2024-09-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='paid')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='payment date')),
                ('payment_code', models.CharField(blank=True, max_length=256, null=True, verbose_name='payment code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user cart',
                'verbose_name_plural': 'users cart',
            },
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='final price')),
                ('product_count', models.IntegerField(verbose_name='product count')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
                ('user_cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='user_cart')),
            ],
            options={
                'verbose_name': 'cart product',
                'verbose_name_plural': 'carts products',
            },
        ),
    ]
