# Generated by Django 5.0.3 on 2024-09-09 16:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='category title')),
                ('title_fa', models.CharField(max_length=256, null=True, unique=True, verbose_name='category title')),
                ('title_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='category title')),
                ('slug', models.CharField(max_length=256, unique=True, verbose_name='link')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_delete', models.BooleanField(verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'grand parent category',
                'verbose_name_plural': 'grand parents categories',
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='category title')),
                ('title_fa', models.CharField(max_length=256, null=True, unique=True, verbose_name='category title')),
                ('title_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='category title')),
                ('slug', models.CharField(max_length=256, unique=True, verbose_name='link')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_delete', models.BooleanField(verbose_name='deleted')),
                ('parent_parent_category', models.ManyToManyField(to='products.parentparentcategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'parent category',
                'verbose_name_plural': 'parent categories',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=56, unique=True, verbose_name='category title')),
                ('title_fa', models.CharField(db_index=True, max_length=56, null=True, unique=True, verbose_name='category title')),
                ('title_en', models.CharField(db_index=True, max_length=56, null=True, unique=True, verbose_name='category title')),
                ('url_title', models.CharField(db_index=True, max_length=280, unique=True, verbose_name='link')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_delete', models.BooleanField(verbose_name='deleted')),
                ('parent_category', models.ManyToManyField(to='products.parentcategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56, unique=True, verbose_name='product title')),
                ('title_fa', models.CharField(max_length=56, null=True, unique=True, verbose_name='product title')),
                ('title_en', models.CharField(max_length=56, null=True, unique=True, verbose_name='product title')),
                ('image', models.ImageField(null=True, upload_to='images/products', verbose_name='product image')),
                ('image_bg', models.ImageField(null=True, upload_to='images/products', verbose_name='product bg image')),
                ('price', models.IntegerField(verbose_name='price')),
                ('inventory', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='inventory')),
                ('short_description', models.CharField(db_index=True, max_length=224, verbose_name='short description')),
                ('short_description_fa', models.CharField(db_index=True, max_length=224, null=True, verbose_name='short description')),
                ('short_description_en', models.CharField(db_index=True, max_length=224, null=True, verbose_name='short description')),
                ('description', models.TextField(db_index=True, verbose_name='description')),
                ('description_fa', models.TextField(db_index=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(db_index=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(default='', max_length=224, unique=True, verbose_name='link')),
                ('addDate', models.DateField(blank=True, null=True, verbose_name='add date')),
                ('releaseDate', models.DateField(blank=True, verbose_name='release date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_delete', models.BooleanField(verbose_name='deleted')),
                ('discount', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95)], default=0, verbose_name='discount')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ManyToManyField(to='products.productcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='add date')),
                ('comment', models.TextField(verbose_name='comment')),
                ('confirm_by_admin', models.BooleanField(default=True, verbose_name='confirm by admin')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comment', to='products.productcomment', verbose_name='parent comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'product comment',
                'verbose_name_plural': 'product comments',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/gallery_product', verbose_name='gallery image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product gallery',
                'verbose_name_plural': 'product gallery',
            },
        ),
        migrations.CreateModel(
            name='ProductVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25, verbose_name='user ip')),
                ('user', models.IntegerField(blank=True, null=True, verbose_name='user id')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'visits',
                'verbose_name_plural': 'visits',
            },
        ),
    ]
